INSERT INTO Status (name) VALUES
  ('Active'),
  ('IPO'),
  ('Acquired'),
  ('Pre2003'),
  ('Relocated');

INSERT INTO Sector (name) VALUES
  ('Santé'),
  ('E-commerce'),
  ('Marketing'),
  ('Banque'),
  ('Multimédia'),
  ('Informatique'),
  ('Fintech'),
  ('Environnement'),
  ('Immobilier'),
  ('Assurance'),
  ('Transport'),
  ('IA'),
  ('Energie'),
  ('Industriel'),
  ('Cryptomonnaie'),
  ('Financement');

INSERT INTO Startup (name, founded_year, valuation, website, description, sector_id, status_id)
VALUES
  ('Doctolib', 2013, 6100000000, 'https://www.doctolib.fr', 'Plateforme de gestion de rendez-vous médicaux', (SELECT sector_id FROM Sector WHERE name = 'Santé'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Back Market', 2014, 5800000000, 'https://www.backmarket.fr', 'Marketplace de produits électroniques reconditionnés', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Contentsquare', 2012, 5600000000, 'https://www.contentsquare.com', 'Analyse de l''expérience utilisateur', (SELECT sector_id FROM Sector WHERE name = 'Marketing'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Qonto', 2016, 5000000000, 'https://www.qonto.com', 'Banque en ligne pour professionnels', (SELECT sector_id FROM Sector WHERE name = 'Banque'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Sorare', 2018, 4600000000, 'https://www.sorare.com', 'Jeu de fantasy football basé sur la blockchain', (SELECT sector_id FROM Sector WHERE name = 'Multimédia'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Mirakl', 2012, 3500000000, 'https://www.mirakl.com', 'Marketplace B2B et B2C', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Veepee', 2001, 3000000000, 'https://www.veepee.fr', 'Ventes événementielles en ligne', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('ManoMano', 2013, 2600000000, 'https://www.manomano.fr', 'Marketplace de bricolage et jardinage', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Mistral AI', 2023, 2000000000, 'https://www.mistral.ai', 'Intelligence artificielle générative', (SELECT sector_id FROM Sector WHERE name = 'IA'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Verkor', 2020, 2000000000, 'https://www.verkor.com', 'Batteries bas carbone', (SELECT sector_id FROM Sector WHERE name = 'Energie'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Exotec', 2015, 2000000000, 'https://www.exotec.com', 'Robots logistiques pour entrepôts', (SELECT sector_id FROM Sector WHERE name = 'Industriel'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('PayFit', 2015, 2000000000, 'https://www.payfit.com', 'Gestion de paie et RH', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('BlaBlaCar', 2006, 2000000000, 'https://www.blablacar.fr', 'Covoiturage longue distance', (SELECT sector_id FROM Sector WHERE name = 'Transport'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Ankorstore', 2019, 1980000000, 'https://www.ankorstore.com', 'Marketplace B2B pour commerçants', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Voodoo', 2013, 1700000000, 'https://www.voodoo.io', 'Jeux mobiles', (SELECT sector_id FROM Sector WHERE name = 'Multimédia'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Vestiaire Collective', 2009, 1700000000, 'https://www.vestiairecollective.com', 'Marketplace de mode d''occasion', (SELECT sector_id FROM Sector WHERE name = 'E-commerce'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Alan', 2016, 1680000000, 'https://www.alan.com', 'Assurance santé digitale', (SELECT sector_id FROM Sector WHERE name = 'Santé'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Ledger', 2014, 1500000000, 'https://www.ledger.com', 'Portefeuilles de cryptomonnaies', (SELECT sector_id FROM Sector WHERE name = 'Cryptomonnaie'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('NW Groupe', 2009, 1500000000, 'https://www.nw-groupe.com', 'Energies renouvelables', (SELECT sector_id FROM Sector WHERE name = 'Environnement'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('IAD', 2008, 1400000000, 'https://www.iadfrance.fr', 'Réseau immobilier', (SELECT sector_id FROM Sector WHERE name = 'Immobilier'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Dental Monitoring', 2014, 1200000000, 'https://www.dental-monitoring.com', 'Suivi dentaire à distance', (SELECT sector_id FROM Sector WHERE name = 'Santé'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Younited', 2009, 1100000000, 'https://www.younited-credit.com', 'Crédit en ligne', (SELECT sector_id FROM Sector WHERE name = 'Financement'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Swile', 2018, 1000000000, 'https://www.swile.co', 'Titres-restaurant dématérialisés', (SELECT sector_id FROM Sector WHERE name = 'Fintech'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Pennylane', 2020, 1000000000, 'https://www.pennylane.com', 'Comptabilité en ligne', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Pigment', 2019, 1000000000, 'https://www.pigment.com', 'Planification financière', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Spendesk', 2016, 1000000000, 'https://www.spendesk.com', 'Gestion des dépenses', (SELECT sector_id FROM Sector WHERE name = 'Fintech'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Shift Technology', 2014, 1000000000, 'https://www.shift-technology.com', 'Détection de fraude pour assurances', (SELECT sector_id FROM Sector WHERE name = 'Assurance'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Lydia', 2013, 1000000000, 'https://www.lydia-app.com', 'Paiement mobile', (SELECT sector_id FROM Sector WHERE name = 'Fintech'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('EcoVadis', 2007, 1000000000, 'https://www.ecovadis.com', 'Évaluation RSE des entreprises', (SELECT sector_id FROM Sector WHERE name = 'Environnement'), (SELECT status_id FROM Status WHERE name = 'Active')),
  ('Ivalua', 2000, 1000000000, 'https://www.ivalua.com', 'Gestion des achats', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Pre2003')),
  ('OVHcloud', 1999, 1200000000, 'https://www.ovhcloud.com', 'Hébergement cloud', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Pre2003')),
  ('Kyriba', 2000, 1000000000, 'https://www.kyriba.com', 'Gestion de trésorerie', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Relocated')),
  ('Dataiku', 2013, 1100000000, 'https://www.dataiku.com', 'Plateforme d''IA et de data science', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Relocated')),
  ('Aircall', 2014, 1000000000, 'https://www.aircall.io', 'Téléphonie cloud', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Relocated')),
  ('Owkin', 2016, 1000000000, 'https://www.owkin.com', 'IA pour la santé', (SELECT sector_id FROM Sector WHERE name = 'Santé'), (SELECT status_id FROM Status WHERE name = 'Relocated')),
  ('Front', 2013, 1000000000, 'https://www.front.com', 'Messagerie collaborative', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'Relocated')),
  ('Criteo', 2005, 1500000000, 'https://www.criteo.com', 'Publicité personnalisée sur internet', (SELECT sector_id FROM Sector WHERE name = 'Marketing'), (SELECT status_id FROM Status WHERE name = 'IPO')),
  ('Meero', 2016, 1000000000, 'https://www.meero.com', 'Plateforme de photographes', (SELECT sector_id FROM Sector WHERE name = 'Multimédia'), (SELECT status_id FROM Status WHERE name = 'Acquired')),
  ('Talend', 2005, 1000000000, 'https://www.talend.com', 'Intégration de données', (SELECT sector_id FROM Sector WHERE name = 'Informatique'), (SELECT status_id FROM Status WHERE name = 'IPO')),
  ('Deezer', 2007, 1000000000, 'https://www.deezer.com', 'Streaming musical', (SELECT sector_id FROM Sector WHERE name = 'Multimédia'), (SELECT status_id FROM Status WHERE name = 'IPO')),
  ('Believe', 2005, 1000000000, 'https://www.believe.com', 'Distribution musicale digitale', (SELECT sector_id FROM Sector WHERE name = 'Multimédia'), (SELECT status_id FROM Status WHERE name = 'IPO')); 